name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        python -m venv venv
        .\venv\Scripts\Activate.ps1
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Formatear código con Black
      run: |
        .\venv\Scripts\Activate.ps1
        black --check src/ tests/ notebooks/

    - name: Ordenar importaciones con isort
      run: |
        .\venv\Scripts\Activate.ps1
        isort --check-only src/ tests/

    - name: Verificar estilo con Flake8
      run: |
        .\venv\Scripts\Activate.ps1
        flake8 src/ tests/

    - name: Ejecutar pruebas unitarias
      run: |
        .\venv\Scripts\Activate.ps1
        pytest tests/
